- hosts: all
  become: yes
  become_user: root

  vars:
  #    sshd_config_path: /tmp/sshd_config
      sshd_config_path: /etc/ssh/sshd_config

  tasks:
  # 拷贝krb5.conf文件到/etc目录下
    - name: copy krb5.conf to /etc
      copy: src=../../depend/config/kerberos/krb5.conf  dest=/etc/ mode=0644



  # 修改sshd_config使用Kerberos登录
    - name: Open KerberosAuthentication...
      lineinfile:
        dest: "{{sshd_config_path}}"
        regexp: "^#KerberosAuthentication"
        line: "KerberosAuthentication yes"

    - name: Open KerberosTicketCleanup...
      lineinfile:
        dest: "{{sshd_config_path}}"
        regexp: "^#KerberosTicketCleanup"
        line: "KerberosTicketCleanup yes"

    - name: Open GSSAPIAuthentication...
      lineinfile:
        dest: "{{sshd_config_path}}"
        regexp: "^#GSSAPIAuthentication"
        line: "GSSAPIAuthentication yes"

    - name: Open GSSAPICleanupCredentials...
      lineinfile:
        dest: "{{sshd_config_path}}"
        regexp: "^#GSSAPICleanupCredentials"
        line: "GSSAPICleanupCredentials yes"

    - name: Close PasswordAuthentication...
      lineinfile:
        dest: "{{sshd_config_path}}"
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
    - name: restart sshd...
      service: name=sshd state=restarted
      ignore_errors: yes


  # 修改主机名与dns保持一致,cdh的服务器请注释
    - name: Set hostname
      hostname: name={{ hostname }}
#      when: "{{system_type}}==no"
  # 创建.k5login
    - name: touch .k5login
      file: "path=/home/{{systemUser}}/.k5login mode=0644 state=touch"