---
- hosts: all
  gather_facts: no

  tasks:

  - name: install ssh key
    authorized_key: user=ops-admin
                    key="{{ lookup('file', '/home/ops-admin/.ssh/id_rsa.pub') }}"
                    state=present