---
- name: Tomcat deploy
  hosts: all
  become: yes
  become_user: root

  tasks:
#    - name: touch file
#      shell: touch /home/ops-admin/icarbonx.file
    - name: copy flanneld.service to /etc
      shell:
        cmd: |
          cat <<EOF > /lib/systemd/system/flanneld.service
          [Unit]
          Description=Flanneld
          Documentation=https://github.com/coreos/flannel
          After=network.target
          Before=docker.service
          
          [Service]
          User=root
          ExecStart=/opt/bin/flanneld \
            --etcd-endpoints="${TEST_NODES}" \
            --iface={{node}} \
            --ip-masq
          Restart=on-failure
          Type=notify
          LimitNOFILE=65536
          EOF
          
