---
- name: Tomcat deploy
  hosts: all
  become: yes
  become_user: root

  tasks:
#    - name: touch file
#      shell: touch /home/ops-admin/icarbonx.file
    - name: copy flanneld.service to /etc
      copy: src=../../depennd/kubernetes/flanneld.service  dest=/lib/systemd/system/ mode=0644

