apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  namespace: default
  labels:
    name: redis-master
    version: v1
spec:
  replicas: 1
  selector:
    name: redis-master
    version: v1
  template:
    metadata:
      labels:
        name: redis-master
        version: v1
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/common/redis-master:2.8.19
          name: redis-master
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 6379
            protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/redis
            - name: redis-config
              mountPath: /usr/local/etc/redis
      volumes:
        - name: data
          hostPath:
            path: /data/redis
        - name: redis-config
          configMap:
            name: redis-config
            items:
            - key: redis-master
              path: redis.conf
      nodeSelector:
        kubernetes.io/hostname: 10.47.0.26


---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: component
  labels:
    name: redis-master

spec:
  externalIPs:
    - 10.47.0.26
  ports:
    - name: master
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: redis-master

