apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
  namespace: default
  labels:
    name: redis-sentinel
    version: v1
spec:
  replicas: 3
  selector:
    name: redis-sentinel
    version: v1
  template:
    metadata:
      labels:
        name: redis-sentinel
        version: v1
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/develop/redis-cluster-sentinel
          name: redis-sentinel
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 26379
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            request:
              cpu: "0.2"
              memory: "256Mi"

          volumeMounts:
            - name: redis-storage
              mountPath: /var/lib/redis
      volumes:
        - name: redis-storage
          hostPath:
            path: /data/redis
      nodeSelector:
        kubernetes.io/hostname: 10.47.0.251


---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: default
  labels:
    name: redis-sentinel
spec:
  externalIPs:
    - 10.27.0.251
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: 26379
  selector:
    name: redis-sentinel
