apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: redis-sentinel
  name: redis-sentinel
  namespace: default
spec:
  replicas: 3
  selector:
    name: redis-sentinel
  template:
      labels:
        name: redis-sentinel
    spec:
      containers:
      - image: ccr.ccs.tencentyun.com/beta/redis-cluster-sentienl
        imagePullPolicy: IfNotPresent
        name: redis-sentinel
        ports:
        - containerPort: 26379
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/redis
          name: redis-storage
      volumes:
      - hostPath:
          path: /mdata/redis
        name: redis-storage
      nodeSelector:
        kubernetes.io/hostname: 10.47.0.251

---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: default
  labels:
    name: redis-sentinel
spec:
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: 26379
  selector:
    name: redis-sentinel
