apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: redis-รง
    version: v1
  name: redis-sentinel
  namespace: default
spec:
  replicas: 3
  selector:
    name: redis-sentinel
    version: v1
  template:
    metadata:
      labels:
        name: redis-sentinel
        version: v1
    spec:
      containers:
      - image: ccr.ccs.tencentyun.com/develop/redis-cluster-sentinel
        imagePullPolicy: IfNotPresent
        name: redis-sentinel
        ports:
        - containerPort: 26379
          protocol: TCP
        volumeMounts:
        - name: redis-storage
          mountPath: /var/lib/redis
        - name: redis-conf
          mountPath: /etc/redis/sentinel.conf
          subPath: sentinel.conf
        - name: redis-run
          mountPath: /etc/redis/run.sh
          subPath: run.sh
      volumes:
      volumes:
      - name: redis-storage
        hostPath:
          path: /data/redis
      - name: redis-conf
        configMap:
          name: redis-config
          items:
          - key: redis-sentinel-conf
            path: sentinel.conf
      - name: redis-run
        configMap:
          name: redis-config
          items:
          - key: redis-sentinel-run
            path: run.sh
      nodeSelector:
        kubernetes.io/hostname: 10.47.0.251


---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: default
  labels:
    name: redis-sentinel
spec:
  ports:
    - name: sentinel
      port: 26379
      protocol: TCP
      targetPort: 26379
  selector:
    name: redis-sentinel
