#!/usr/bin/env bash
COMMON_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && echo "$PWD")"
. $COMMON_PATH/../../config/installConfig


#验证ip地址的正确性
function ip_valid()  {
    echo $1 | grep "^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$" > /dev/null
    if [ $? = 1 ]; then
        return 1
    else
        a=`echo $1 | awk -F. '{print $1}'`
        b=`echo $1 | awk -F. '{print $2}'`
        c=`echo $1 | awk -F. '{print $3}'`
        d=`echo $1 | awk -F. '{print $4}'`

        if [ $a -ge 255 -o $a -le 0 -o $b -gt 255 -o $b -lt 0 -o $c -gt 255 -o $c -lt 0 -o $d -gt 255 -o $d -le 0 ]; then
            return 2;
        fi

        #验证是否组播地址
        if [ $a -ge 224 -a $a -le 239 ]; then
            return 3
        fi

        #验证回环
        if [ $a -eq 127 ]; then
            return 4
        fi

    fi
    return 0
}

#设置主机名与dns一致
function sethostname(){
    if [ $# -ne 1 ];then
        echo "ERROR: sethostname param is error."
    fi
    ip=$1;
    local hostname;
    hostname="$HOSTNAME_TYPE-${ip//./-}.$HOSTNAME_EVN.$HOSTNAME_CNAME"
    echo $hostname;
}